Added feature.
crilleengvall/Screenbar pull request #17
Opened 2019-01-19 17:58 UTC by KryptekVoid

Added feature to select the format of a screenshot (JPG/JPEG or PNG). Added a quit button.

2019-01-27 10:09 UTC, crilleengvall requested changes
Hi!

Thanks for the pullrequest. The functionality works well. I've added some comments on stuff that needs fixing.

2019-01-27 10:09 UTC, crilleengvall commented on Screenbar/MainWindowViewController.swift
> +    // Declares Timer to count seconds and creates a screenshot handler for Screenshot.swift.
I'm trying to follow clean code when it comes to comments. I couldn't find the Robert C Martin video where he talks about it. But this explains it a bit: https://www.youtube.com/watch?v=j7oIDSE1MCw
So remove this comment.

2019-01-27 10:09 UTC, crilleengvall commented on Screenbar/MainWindowViewController.swift
> +    // Set the initial values of all the parameters.
This comment isn't necessary

2019-01-27 10:09 UTC, crilleengvall commented on Screenbar/MainWindowViewController.swift
> +    // Save the second interval, path, and option to play sound settings.
Not needed

2019-01-27 10:09 UTC, crilleengvall commented on Screenbar/MainWindowViewController.swift
> +    // Tests to see if settings are valid.
Remove this comment as well

2019-01-27 10:09 UTC, crilleengvall commented on Screenbar/MainWindowViewController.swift
> +        // Convert the seconds to a Double
Remove comment

2019-01-27 10:09 UTC, crilleengvall commented on Screenbar/MainWindowViewController.swift
> +        // Get the path and sound state.
remove comment

2019-01-27 10:09 UTC, crilleengvall commented on Screenbar/MainWindowViewController.swift
> +        // If the seconds were invalid then show an error.
remove comment

2019-01-27 10:09 UTC, crilleengvall commented on Screenbar/MainWindowViewController.swift
> +        else { // Otherwise we hide the error and set the parameters.
remove comment

2019-01-27 10:09 UTC, crilleengvall commented on Screenbar/MainWindowViewController.swift
> +        // If saving the settings is successful; begin automatic screenshot captures.
Also not needed. The comment is explained in the method names.

2019-01-27 10:09 UTC, crilleengvall commented on Screenbar/MainWindowViewController.swift
> +        // If the time is running; display to stop the captures
Remove comment. The method name explains this.

2019-01-27 10:09 UTC, crilleengvall commented on Screenbar/MainWindowViewController.swift
> +    // The logic behind changnig the label text on the Start Capture button.
Remove comment. The Function name tells this story already

2019-01-27 10:09 UTC, crilleengvall commented on Screenbar/MainWindowViewController.swift
> +    // Invalidates the timer and changes the label.
Not necessary. Remove this comment.

2019-01-27 10:09 UTC, crilleengvall commented on Screenbar/MainWindowViewController.swift
> +    // Validates the timer and changes the label.
Remove this comment

2019-01-27 10:09 UTC, crilleengvall commented on Screenbar/MainWindowViewController.swift
> +    // Get the seconds value from the text box.
Method name tells this story already. Remove comment

2019-01-27 10:09 UTC, crilleengvall commented on Screenbar/MainWindowViewController.swift
> +    // Set Play sound state
Method name tells this story already. Remove comment

2019-01-27 10:09 UTC, crilleengvall commented on Screenbar/MainWindowViewController.swift
> +    // Shows error message
Method name tells this story already. Remove comment

2019-01-27 10:09 UTC, crilleengvall commented on Screenbar/MainWindowViewController.swift
> +    // Hides error message
Method name tells this story already. Remove comment

2019-01-27 10:09 UTC, crilleengvall commented on Screenbar/MainWindowViewController.swift
> +    // Sets the path
Method name tells this story already. Remove comment

2019-01-27 10:09 UTC, crilleengvall commented on Screenbar/MainWindowViewController.swift
> +    // Hides the app
Method name tells this story already. Remove comment

2019-01-27 10:09 UTC, crilleengvall commented on Screenbar/MainWindowViewController.swift
> +    // Exits the application.
Method name tells this story already. Remove comment

2019-01-27 10:09 UTC, crilleengvall commented on Screenbar/MainWindowViewController.swift
> +// Helper function inserted by Swift 4.2 migrator.
Not needed. remove.

2019-01-27 10:09 UTC, crilleengvall commented on Screenbar/ScreenShot.swift
> +    // Returns the date. This will be used to name the screenshot.
Not needed. Remove.

2019-01-27 10:09 UTC, crilleengvall commented on Screenbar/ScreenShot.swift
> +        // Get the date string from the previous function.
Remove comment

2019-01-27 10:09 UTC, crilleengvall commented on Screenbar/ScreenShot.swift
> +        // Create a process and take a screenshot with it.
remove comment

2019-01-27 10:09 UTC, crilleengvall commented on Screenbar/ScreenShot.swift
> +        // If the Play sound with capture box is unchecked we silence the command..
remove comment

2019-01-27 10:09 UTC, crilleengvall commented on Screenbar/ScreenShot.swift
> +            // screenshot -x <filePath> # -x means do not play a sound.
Remove comment

2019-01-27 10:09 UTC, crilleengvall commented on Screenbar/ScreenShot.swift
> +        // 1 = PNG
Remove comments

2019-01-27 10:09 UTC, crilleengvall commented on Screenbar/ScreenShot.swift
> +        // Append the remainder of the arguments to the command. See man /usr/sbin/screenshot for more options.
Remove comments

2019-01-27 10:09 UTC, crilleengvall commented on Screenbar/ScreenShot.swift
> +        // Launch the task.
Remove comment. the method name already tells us this.

2019-01-27 10:09 UTC, crilleengvall commented on Screenbar.xcodeproj/project.pbxproj
> +				PRODUCT_BUNDLE_IDENTIFIER = com.KalebHawkins.Screenbar;
bundle identifier should not change

2019-01-27 10:09 UTC, crilleengvall commented on Screenbar.xcodeproj/project.pbxproj
> +				PRODUCT_BUNDLE_IDENTIFIER = com.KalebHawkins.Screenbar;
bundle identifier should not change

2019-01-27 10:09 UTC, crilleengvall commented on README.md
> -## Installation
The installation part should not be removed

2019-01-27 10:09 UTC, crilleengvall commented on README.md
> -![Screenbar menu bar](https://www.screenbar.net/assets/images/screenbar-window.png "Screenbar main")
The screenshot needs to be updated. Not removed. 
You could send me one and i can host it.

2019-01-27 10:09 UTC, crilleengvall commented on Screenbar/MainWindowView.xib
> +                <outlet property="quit" destination="zfO-Iw-jKV" id="xnl-cT-naP"/>
Position this button to the left so that is aligned with the rest of the controls above (The checkbox for sound etc.)

2019-01-28 02:55 UTC, KalebHawkins reviewed
I've updated the repository with the changes. If I missed anything please let me know.

2019-01-28 02:55 UTC, KalebHawkins commented on README.md
> -![Screenbar menu bar](https://www.screenbar.net/assets/images/screenbar-window.png "Screenbar main")
Sure thing. I have attached a new screenshot here.
<img width="482" alt="screen shot 2019-01-27 at 8 37 41 pm" src="https://user-images.githubusercontent.com/13454496/51811628-6efa6d80-2273-11e9-8f4f-761773f937fd.png">

2019-02-05 19:43 UTC, crilleengvall commented
> I've updated the repository with the changes. If I missed anything please let me know.

Thx!
Sry for being this slow with the pullrequst. I've got a lot of stuff todo at the moment. I'll take a look at it as soon as i can.

2019-02-05 22:02 UTC, KalebHawkins commented
No problems at all. I’ve been busy myself. So no worries.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________
From: Christian Engvall <notifications@github.com>
Sent: Tuesday, February 5, 2019 1:43 PM
To: crilleengvall/Screenbar
Cc: Kaleb Hawkins; Author
Subject: Re: [crilleengvall/Screenbar] Added feature. (#17)


I've updated the repository with the changes. If I missed anything please let me know.

Thx!
Sry for being this slow with the pullrequst. I've got a lot of stuff todo at the moment. I'll take a look at it as soon as i can.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/crilleengvall/Screenbar/pull/17#issuecomment-460776418>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AM1MoDG0tKnwiNzOOcTGImLFant0PiGhks5vKd7ugaJpZM4aJQUX>.

2021-11-09 19:08 UTC, closed without merging